version: '3'

services:
  postgresql:
    container_name: postgres
    image: postgres
    volumes:
    - ./postgres_data:/var/lib/postgresql/data
    environment:
    - POSTGRES_DB=keycloak
    - POSTGRES_USER=keycloak
    - POSTGRES_PASSWORD=password
    networks:
    - keycloak-network
    restart: always

  keycloak:
    container_name: keycloak
    image: jboss/keycloak
    ports:
    - "9191:8080"
    depends_on:
    - postgresql
    environment:
    - VIRTUAL_HOST=auth.barium.se
    - VIRTUAL_PORT=8080
    - KEYCLOAK_USER=admin
    - KEYCLOAK_PASSWORD=admin
    - POSTGRES_PASSWORD=password
    - POSTGRES_PORT_5432_TCP_ADDR=postgresql
    - POSTGRES_PORT_5432_TCP_PORT=5432
    networks:
    - keycloak-network
    restart: always

networks:
  keycloak-network:
